<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class JurnalumumModel extends CI_Model
{

    public $table = 'tbl_jurnal_umum';
    public $id = 'no_jurnal';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    //Query manual
	function manualQuery($q)
	{
		return $this->db->query($q);
	}

    // datatables
    function json() {
        $this->datatables->select('no_jurnal,tgl_jurnal,ket,no_bukti,no_rek,debet,kredit,username,tgl_insert');
        $this->datatables->from('tbl_jurnal_umum');
        //add this line for join
        //$this->datatables->join('table2', 'tbl_jurnal_umum.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('jurnalumum/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
            ".anchor(site_url('jurnalumum/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
                ".anchor(site_url('jurnalumum/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'no_jurnal');
        return $this->datatables->generate();
    }

    function get_no_jurnal(){
        $q = $this->db->query("SELECT MAX(RIGHT(no_jurnal,4)) AS kd_max FROM tbl_jurnal_umum WHERE DATE(tgl_jurnal)=CURDATE()");
        $kd = "";
        if($q->num_rows()>0){
            foreach($q->result() as $k){
                $tmp = ((int)$k->kd_max)+1;
                $kd = sprintf("%04s", $tmp);
            }
        }else{
            $kd = "0001";
        }
        date_default_timezone_set('Asia/Jakarta');
        return date('dmy').$kd;
    }

    public function CariNamaRek($id){
		$text = "SELECT * FROM tbl_rekening WHERE no_rek='$id'";
		$data = $this->JurnalumumModel->manualQuery($text);
		if($data->num_rows() > 0 ){
			foreach($data->result() as $t){
				$hasil = $t->nama_rek;
			}
		}else{
			$hasil = 0;
		}
		return $hasil;
	}

    public function listRekNama() {
        $sql= "SELECT * FROM tbl_rekening ORDER BY no_rek ASC";
			$query=$this->db->query($sql);
			return $query->result_array();
    }


    // function simpan_jurnal($no_jurnal){
    //     $hasil=$this->db->query("INSERT INTO tbl_jurnal_umum(no_jurnal) VALUES ('$no_jurnal')");
    //     return $hasil;
    // }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('no_jurnal', $q);
	$this->db->or_like('tgl_jurnal', $q);
	$this->db->or_like('ket', $q);
	$this->db->or_like('no_bukti', $q);
	$this->db->or_like('debet', $q);
	$this->db->or_like('kredit', $q);
	$this->db->or_like('username', $q);
	$this->db->or_like('tgl_insert', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('no_jurnal', $q);
	$this->db->or_like('tgl_jurnal', $q);
	$this->db->or_like('ket', $q);
	$this->db->or_like('no_bukti', $q);
	$this->db->or_like('debet', $q);
	$this->db->or_like('kredit', $q);
	$this->db->or_like('username', $q);
	$this->db->or_like('tgl_insert', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file JurnalumumModel.php */
/* Location: ./application/models/JurnalumumModel.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-02-22 16:02:32 */
/* http://harviacode.com */