<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class JurnalPenyesuaianModel extends CI_Model
{

    public $table = 'tbl_jurnal_penyesuaian';
    public $id = 'no_jurnal';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('no_jurnal,tgl_jurnal,no_rek,debet,kredit,username,tgl_insert');
        $this->datatables->from('tbl_jurnal_penyesuaian');
        //add this line for join
        //$this->datatables->join('table2', 'tbl_jurnal_penyesuaian.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('jurnalpenyesuaian/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
            ".anchor(site_url('jurnalpenyesuaian/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
                ".anchor(site_url('jurnalpenyesuaian/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'no_jurnal');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('no_jurnal', $q);
	$this->db->or_like('tgl_jurnal', $q);
	$this->db->or_like('debet', $q);
	$this->db->or_like('kredit', $q);
	$this->db->or_like('username', $q);
	$this->db->or_like('tgl_insert', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('no_jurnal', $q);
	$this->db->or_like('tgl_jurnal', $q);
	$this->db->or_like('debet', $q);
	$this->db->or_like('kredit', $q);
	$this->db->or_like('username', $q);
	$this->db->or_like('tgl_insert', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file JurnalPenyesuaianModel.php */
/* Location: ./application/models/JurnalPenyesuaianModel.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-02-22 16:03:11 */
/* http://harviacode.com */