<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Penjualanhargamodel extends CI_Model
{

    public $table = 'tbl_penjualan_harga';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id,id_barang,qty,harga_jual_satuan,total_harga_jual,tanggal_transaksi,photo_bukti');
        $this->datatables->from('tbl_penjualan_harga');
        //add this line for join
        //$this->datatables->join('table2', 'tbl_penjualan_harga.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('penjualanharga/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
            ".anchor(site_url('penjualanharga/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
                ".anchor(site_url('penjualanharga/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('id_barang', $q);
	$this->db->or_like('qty', $q);
	$this->db->or_like('harga_jual_satuan', $q);
	$this->db->or_like('total_harga_jual', $q);
	$this->db->or_like('tanggal_transaksi', $q);
	$this->db->or_like('photo_bukti', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('id_barang', $q);
	$this->db->or_like('qty', $q);
	$this->db->or_like('harga_jual_satuan', $q);
	$this->db->or_like('total_harga_jual', $q);
	$this->db->or_like('tanggal_transaksi', $q);
	$this->db->or_like('photo_bukti', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Penjualanhargamodel.php */
/* Location: ./application/models/Penjualanhargamodel.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-02-21 09:03:39 */
/* http://harviacode.com */