<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class SaldoAwalModel extends CI_Model
{

    public $table = 'tbl_saldo_awal';
    public $id = 'periode';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('periode,no_rek,debet,kredit,tgl_insert,username');
        $this->datatables->from('tbl_saldo_awal');
        //add this line for join
        //$this->datatables->join('table2', 'tbl_saldo_awal.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('saldoawal/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
            ".anchor(site_url('saldoawal/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
                ".anchor(site_url('saldoawal/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'periode');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('periode', $q);
	$this->db->or_like('debet', $q);
	$this->db->or_like('kredit', $q);
	$this->db->or_like('tgl_insert', $q);
	$this->db->or_like('username', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('periode', $q);
	$this->db->or_like('debet', $q);
	$this->db->or_like('kredit', $q);
	$this->db->or_like('tgl_insert', $q);
	$this->db->or_like('username', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file SaldoAwalModel.php */
/* Location: ./application/models/SaldoAwalModel.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-02-22 16:01:38 */
/* http://harviacode.com */